#!/usr/bin/env node
/**
 * Generate docs/ui/components.md from atomic-spec + ui component registry.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { UI_COMPONENT_REGISTRY } from '../../src/ui/pages/uiKitPage.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const SPEC_ROOT = join(ROOT, 'packages', 'atomic-spec');
const OUT_PATH = join(ROOT, 'docs', 'ui', 'components.md');

function readSpecTitles(subdir) {
  const map = new Map();
  const dir = join(SPEC_ROOT, subdir);
  try {
    for (const file of readdirSync(dir).filter((name) => name.endsWith('.bvc'))) {
      const text = readFileSync(join(dir, file), 'utf8');
      const titleMatch = text.match(/^#([^<\[]+)/m);
      const id = file.replace(/\.bvc$/, '');
      map.set(`${subdir}/${id}`, titleMatch ? titleMatch[1].trim() : id);
    }
  } catch {
    // optional until specs exist
  }
  return map;
}

function main() {
  const specTitles = new Map([
    ...readSpecTitles('atoms'),
    ...readSpecTitles('molecules'),
    ...readSpecTitles('organisms'),
  ]);
  const lines = [
    '# UI Components Catalog',
    '',
    'Generated by `@iohasc/docs-generator` from `packages/atomic-spec` and `src/ui/*`.',
    '',
    '| Component | Layer | Spec | Work Graph preview |',
    '|-----------|-------|------|--------------------|',
  ];

  for (const entry of UI_COMPONENT_REGISTRY) {
    const specKey = `${entry.layer === 'atom' ? 'atoms' : `${entry.layer}s`}/${entry.id}`.replace('molecules/tabs', 'molecules/tabs-group');
    const specTitle = [...specTitles.entries()].find(([key]) => key.endsWith(`/${entry.id}`) || key.includes(entry.id))?.[1] ?? '—';
    lines.push(`| \`${entry.id}\` | ${entry.layer} | ${specTitle} | [/dev/ui-kit#ui-kit-${entry.id}](/dev/ui-kit#ui-kit-${entry.id}) |`);
  }

  for (const layer of ['atom', 'molecule', 'organism']) {
    const plural = layer === 'atom' ? 'atoms' : `${layer}s`;
    const entries = UI_COMPONENT_REGISTRY.filter((entry) => entry.layer === layer);
    if (entries.length === 0) continue;
    lines.push('', `## ${plural.charAt(0).toUpperCase()}${plural.slice(1)}`, '');
    for (const entry of entries) {
      lines.push(`### ${entry.title} (\`${entry.id}\`)`, '');
      lines.push(`Layer: **${entry.layer}**`, '');
      lines.push(`Preview: \`/dev/ui-kit#ui-kit-${entry.id}\``, '');
      lines.push('');
    }
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`wrote ${OUT_PATH}`);
}

main();
